[package]
name = "join-autumn"
version = "0.1.0"
authors = ["hyziri <hyziri@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }

dioxus = { version = "0.5.6", features = ["fullstack", "router"] }
dioxus-helmet = { git = "https://github.com/dioxus-community/dioxus-helmet.git" }
dioxus-free-icons = { version = "0.8.6", features = ["font-awesome-brands"] }

# Debug
dioxus-logger = "0.5.1"
manganis = "0.2.2"

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
