services:
  autumn-homepage:
    image: hyziri/autumn-homepage
    restart: unless-stopped
    environment:
      - APPLICATION_EMAIL=${APPLICATION_EMAIL}
    volumes:
      - autumn-homepage:/app/data

volumes:
  autumn-homepage:
