services:
  autumn-homepage:
    build: .
    restart: unless-stopped
    environment:
      - APPLICATION_EMAIL=${APPLICATION_EMAIL}
    volumes:
      - autumn-homepage:/app/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -H 'Accept: text/html' http://localhost:8080 || exit 1",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  autumn-homepage:
